### ISSUE TITLE
Prices are not displayed in the emails sent from craigwatcher.

### ISSUE THREAD

**Issue by olek** [brighton36/libcraigscrape#3]
Just as subject said, prices are not included in the output of craigwatcher emails.

**Comment by brighton36** [comment]
Seems fixed now. Also Note that I switched the library over to using the 'money' gem now.

**Comment by olek** [comment]
I have a fix for it on my fork as well. I will wait trying your version, last time I tried it (couple days ago) it was sporadically dying on me with date related errors.

Thank you for keeping it up!

**Comment by brighton36** [comment]
It should be pretty stable now - but I am planning on a commit in the next
hour or so . Keep me posted when you get around to it!

**Comment by brighton36** [comment]
Actually -  I think I might have figured out what bug you were referencing, apparently prices aren't always parsing on the listings. I'm going to re-open this and fix this a bit later.

**Comment by olek** [comment]
Feel free to have a look at the master branch of my fork and cherry-pick
fix from there. I also fixed there another problem with
craigslist occasionally hanging for couple minutes and than giving back
useless timeout page - scraper used to blow up when that happened.
